[project]
name = "hello-crewai-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "crewai>=0.108.0",
    "crewai-tools>=0.38.1",
    "docling>=2.40.0",
    "openai>=1.70.0",
]
